import { useRouter } from "next/router";
import React from 'react'
import Head from "next/head";
import Sidebar from "../components/Common/Sidebar";
import Trending from "../components/Common/Trending";
import { onSnapshot, collection, query, deleteDoc, doc } from "@firebase/firestore";
import { db } from "../firebase";
const Admin = () => {
    const router = useRouter();
    const [hasMounted, setHasMounted] = React.useState(false);
    const [users, setUsers] = React.useState([]);

    const deleteUser = (id) => {
        deleteDoc(doc(db, "users", id));
    }

    React.useEffect(() => {
        setHasMounted(true);
    }, []);

    React.useEffect(() => {
        if(localStorage.getItem('userId') === process.env.NEXT_PUBLIC_ADMIN_ID){
            onSnapshot(query(collection(db, `users`)), 
            (snapshot) => {
                let data = snapshot.docs.map((doc) => doc.data())
                for(let i in snapshot.docs){
                    data[i].id = snapshot.docs[i].id
                }
                setUsers(data)
                console.log(data)
            })
        }
    }, [])
    if (!hasMounted) {
        return null;
    }
    else if(localStorage.getItem('userId') !== process.env.NEXT_PUBLIC_ADMIN_ID){
        router.push('/')
    }
    return(
        <div className="bg-white dark:bg-black"> 
        <Head>
            <title>Chirper - Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className='relative max-w-[1400px] mx-auto'>
            <Sidebar/>
            <div className='flex gap-6'>
            <div className='sm:ml-20 xl:ml-[340px] w-[600px] min-h-screen border-r border-gray-400 text-black dark:text-white py-2'>
            <div className="px-2">
                <div className="admin_title">Admin Interface</div>
                <div className="admin_subtitle">Welcome to the admin page, you have the permission to see all the users of Chirper, and remove accounts</div>
                <div className="mt-6">
                {
                    users.map((user, index) => {
                        return(
                            <div className="py-4 border-2 border-x-0 flex border-gray-300">
                                <div className="text-lg my-auto">
                                    {user.username}
                                </div>
                                <div className="ml-4 text-gray-400 my-auto">
                                    @{user.tag}
                                </div>
                                <div className="ml-auto px-4 py-2 bg-red-600 rounded-lg cursor-pointer" onClick={()=>deleteUser(user.id)}>Delete</div>
                            </div>
                        )
                    })
                }
                </div>
            </div>
            </div>
            <Trending />
            </div>
        </main>
        </div>
        
    )
}
export default Admin;