import Head from 'next/head'
import dynamic from 'next/dynamic'
import Login from "@/components/Login"
import Feed from '../components/Chirps/Feed'
import { AppContext } from '@/contexts/AppContext'
import { useContext, useEffect } from 'react'
import Modal from '@/components/Common/Modal'
import Sidebar from '@/components/Common/Sidebar'
import Trending from '@/components/Common/Trending'
import React from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const [appContext] = useContext(AppContext)
  const [hasMounted, setHasMounted] = React.useState(false);
  React.useEffect(() => {
    setHasMounted(true);
  }, []);
  if (!hasMounted) {
    return null;
  }
  if(hasMounted && localStorage.getItem('userId') == null){
    router.push('/login')
  }
  return (
    <div>
      <Head>
        <title>Chirper - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className=" bg-white dark:bg-black">
        <main className='relative max-w-[1400px] mx-auto bg-white dark:bg-black'>
          <Sidebar/>
          <div className='flex gap-6'>
            <div className='sm:ml-20 xl:ml-[340px] w-[600px] min-h-screen border-r border-gray-400 text-white py-2'>
              <Feed />
            </div>
            <Trending />
          </div>
        </main>
      </div>
    </div>
  )
}
